name       : yaml-cpp
version    : 0.6.2
release    : 2
source     :
    - https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.2.tar.gz : e4d8560e163c3d875fd5d9e5542b5fd5bec810febdcba61481fe5fc4e6b1fd05
license    : MIT
component  : programming.library
summary    : yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec
description: |
    yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
builddeps  :
    - gtest-devel
setup      : |
    %cmake . \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_GMOCK=OFF \
        -DBUILD_GTEST=OFF
build      : |
    %make
install    : |
    %make_install
check      : |
    cd test
    ./run-tests
