name       : yaml-cpp
version    : 0.6.3
release    : 4
source     :
    - https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-0.6.3.tar.gz : 77ea1b90b3718aa0c324207cb29418f5bced2354c2e483a9523d98c3460af1ed
license    : MIT
component  : programming.library
summary    : yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec
description: |
    yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
setup      : |
    %patch -p1 < $pkgfiles/CVE-2017-5950.patch

    # Too borked for Ninja
    %cmake -DENABLE_SHARED_LIBS=ON -DYAML_BUILD_SHARED_LIBS=ON -DLIB_SUFFIX=64 . -B solusBuildDir
build      : |
    %make -C solusBuildDir
install    : |
    %make_install -C solusBuildDir
check      : |
    cd solusBuildDir/test
    ./run-tests
