name       : yaml-cpp
version    : 0.5.3
release    : 1
source     :
    - https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz : ac50a27a201d16dc69a881b80ad39a7be66c4d755eda1f76c3a68781b922af8f
license    : MIT
component  : programming.library
summary    : yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
description: |
    yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
builddeps  :
    - libboost-devel
    - libpth-devel
setup      : |
    sed -i 's:_library_dir lib:_library_dir lib64:g' CMakeLists.txt
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
