name       : yaml-cpp
version    : 0.7.0
release    : 5
source     :
    - https://github.com/jbeder/yaml-cpp/archive/refs/tags/yaml-cpp-0.7.0.tar.gz : 43e6a9fcb146ad871515f0d0873947e5d497a1c9c60c58cb102a97b47208b7c3
homepage   : https://github.com/jbeder/yaml-cpp
license    : MIT
component  : programming.library
summary    : yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec
description: |
    yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
setup      : |
    %patch -p1 < $pkgfiles/empty-cmake-export.patch
    %patch -p1 < $pkgfiles/build-config-install.patch
    %cmake_ninja -DYAML_BUILD_SHARED_LIBS=ON -DINSTALL_GTEST=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
